import React, { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { Lock, Eye, EyeOff, Loader2, CheckCircle2, AlertCircle } from 'lucide-react';
import { supabase } from '../supabaseClient';
import { AuthFrame, ErrorMessage, inputClass } from './LoginPage';

export default function ResetPasswordPage() {
  const [password, setPassword] = useState(''); const [confirm, setConfirm] = useState(''); const [show, setShow] = useState(false); const [loading, setLoading] = useState(false); const [ready, setReady] = useState(false); const [done, setDone] = useState(false); const [error, setError] = useState('');
  useEffect(() => { supabase.auth.getSession().then(({ data }) => setReady(Boolean(data.session))).catch(() => setError('This password reset link has expired. Please request a new one.')); const { data } = supabase.auth.onAuthStateChange((event, session) => { if (event === 'PASSWORD_RECOVERY' || session) setReady(true); }); return () => data.subscription.unsubscribe(); }, []);
  const submit = async (event) => { event.preventDefault(); setError(''); if (!password || !confirm) { setError('Please enter and confirm your new password.'); return; } if (password.length < 12 || !/[A-Z]/.test(password) || !/[0-9]/.test(password) || !/[^A-Za-z0-9]/.test(password)) { setError('Password must be at least 12 characters with uppercase, numbers, and symbols.'); return; } if (password !== confirm) { setError('Passwords do not match.'); return; } setLoading(true); try { const { error: updateError } = await supabase.auth.updateUser({ password }); if (updateError) throw updateError; setDone(true); } catch (_) { setError('This password reset link has expired. Please request a new one.'); } finally { setLoading(false); } };
  return <AuthFrame label="NEW PASSWORD">{done ? <div className="text-center space-y-5"><CheckCircle2 className="w-12 h-12 text-emerald-400 mx-auto" /><h1 className="font-display font-black text-2xl text-white">Password updated</h1><p className="text-slate-400 text-sm">Your password has been changed successfully.</p><Link to="/login" className="inline-flex items-center justify-center w-full py-3.5 rounded-2xl bg-indigo-600 text-white font-bold text-sm">Return to Login</Link></div> : !ready ? <div className="text-center space-y-4"><AlertCircle className="w-10 h-10 text-amber-400 mx-auto" /><h1 className="font-display font-black text-2xl text-white">Reset link unavailable</h1><p className="text-slate-400 text-sm">{error || 'This password reset link has expired. Please request a new one.'}</p><Link to="/forgot-password" className="inline-flex w-full justify-center py-3 rounded-2xl bg-indigo-600 text-white font-bold text-sm">Request New Link</Link></div> : <><h1 className="font-display font-black text-2xl text-white mb-1">Set a new password</h1><p className="text-slate-400 text-sm mb-6">Choose a secure password for your StudyOS account.</p>{error && <ErrorMessage>{error}</ErrorMessage>}<form onSubmit={submit} className="space-y-4 mt-5">{[['new-password','New Password',password,setPassword],['confirm-password','Confirm New Password',confirm,setConfirm]].map(([id,label,value,setValue]) => <div className="space-y-1.5" key={id}><label htmlFor={id} className="block text-[11px] font-bold text-slate-400 uppercase tracking-widest font-mono">{label}</label><div className="relative"><Lock className="absolute left-3.5 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-500" /><input id={id} type={show ? 'text' : 'password'} value={value} onChange={(e) => setValue(e.target.value)} required className={inputClass('pl-10 pr-11')} /><button type="button" onClick={() => setShow((v) => !v)} className="absolute right-3.5 top-1/2 -translate-y-1/2 text-slate-500">{show ? <EyeOff className="w-4 h-4" /> : <Eye className="w-4 h-4" />}</button></div></div>)}<button disabled={loading} className="w-full py-3.5 rounded-2xl bg-indigo-600 text-white font-bold text-sm disabled:opacity-50">{loading ? <Loader2 className="w-4 h-4 animate-spin mx-auto" /> : 'Update Password'}</button></form></>}</AuthFrame>;
}
